version: '2'
services:
  nextcloud:
    image: nextcloud:apache
    container_name: nextcloud
    links:
      - db
    depends_on:
      - db
    networks:
      - nextcloud
    ports:
      - "8080:80"
      - "443:443"
      - "4443:4443"
    environment:
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=secret
      - NEXTCLOUD_TRUSTED_DOMAINS="localhost 192.168.1.166 hubble.local"
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
      - /media/usb0:/media/usb0
      - /media/usb1:/media/usb1
    restart: unless-stopped
  db:
    image: linuxserver/mariadb:arm32v7-latest
    container_name: db
    networks:
      - nextcloud
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

volumes:
  nextcloud:
  db:

networks:
  nextcloud:
    driver: bridge