version: '3'
services:
  nextcloud:
    image: nextcloud:apache
    networks:
      - faraday
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
      - /media/usb0:/media/usb0
      - /media/usb1:/media/usb1
    restart: unless-stopped
  db:
    image: linuxserver/mariadb:arm32v7-latest
    networks:
      - faraday
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped


volumes:
  nextcloud:
  db:

networks:
  faraday:
      driver: bridge