#!/bin/bash
if test $# -eq 0
then
    exit 1
fi

newpassword=$1
hashedpassword=$(php -r "password_hash(${newpassword}, PASSWORD_BCRYPT)")

#RaspAP password
#Future me needs to change these to php var dirs from includes/config.php
if [ -f /etc/raspap/raspap.auth ]
then
	sudo sed -i "2s/.*/${hashedpassword}/" /etc/raspap/raspap.auth
else 
	sudo touch /etc/raspap/raspap.auth
	echo -e "admin\n${hashedpassword}" | sudo tee /etc/raspap/raspap.auth
fi

#PiHole password
sudo pihole -a -p $newpassword

#Nginx password
if [ -f /etc/nginx/.htpasswd ]
then
	sudo htpasswd -b /etc/nginx/.htpasswd admin $newpassword
else 
	sudo htpasswd -c -b /etc/nginx/.htpasswd admin $newpassword
fi
