#!/bin/bash
if [[ $# -eq 0 ]]
then
    exit 1
fi

newpassword=$1
hashedpassword=$(php -r 'echo password_hash('"\"${newpassword}\""', PASSWORD_BCRYPT);')

#RaspAP password
raspapdir=$(php -r "require_once '/var/www/html/wifi/includes/config.php'; echo RASPI_CONFIG;")
if [ -f /etc/raspap/raspap.auth ]
then
	sudo sed -i "2s/.*/$hashedpassword/" /etc/raspap/raspap.auth
else 
	sudo touch /etc/raspap/raspap.auth
	echo -e "admin\n$hashedpassword" | sudo tee /etc/raspap/raspap.auth
fi

#PiHole password
sudo pihole -a -p $newpassword

#Nginx password
if [ -f /etc/nginx/.htpasswd ]
then
	sudo htpasswd -b /etc/nginx/.htpasswd admin $newpassword
else 
	sudo htpasswd -c -b /etc/nginx/.htpasswd admin $newpassword
fi

#Server password
#Place to change username later
username=$(id -nu 1000)
echo "$username:$newpassword" | sudo chpasswd