#!/bin/bash

if [[ $# -eq 0 ]]
then
    exit 1
fi

currenthostname=$(hostname)
newhostname=$1

echo $newhostname | sudo tee /etc/hostname > /dev/null && 
sudo sed -i "s/$currenthostname/$newhostname/g" /etc/hosts && 
sudo sed -i "s/$currenthostname/$newhostname/g" /etc/nginx/sites-available/default