#!/bin/bash
if test $# -eq 0
then
    exit 1
fi

newpassword=$1

#RaspAP password
if [-f /etc/raspap/raspap.auth ]
then
    sudo touch /etc/raspap/raspap.auth
	echo -e "admin\n${newpassword}" | sudo tee /etc/raspap/raspap.auth
else 
	sudo sed -i "2s/.*/${newpassword}/" /etc/raspap/raspap.auth
fi

#PiHole password
sudo pihole -a -p $newpassword

#Nginx password
if [-f /etc/nginx/.htpasswd ]
then
	sudo htpasswd -c -b /etc/nginx/.htpasswd admin $newpassword
else 
	sudo htpasswd -b /etc/nginx/.htpasswd admin $newpassword
fi
