#!/bin/bash
IP=$(ip route show | grep -i 'default via'| awk '{print $7}')
ROUTERIP=$(ip route show | grep -i 'default via'| awk '{print $3}')

APBLOCKIPR=$(cat /etc/nginx/blockips.conf | grep -oP '\d.*\d')
SSHBLOCKIPR=$(cat /etc/hosts.deny | grep -oP "(\d{1,}.)(\d{1,}.)(\d{1,}.)")
APIP=$(grep 'ip_address = ' /etc/raspap/networking/wlan1.ini | cut -d\  -f3)
APIPRSHORT=$(echo $APIP | grep -oP "(\d{1,}.)(\d{1,}.)(\d{1,}.)")
APIPR="${APIPRSHORT}0/$(grep 'ip_address = ' /etc/raspap/networking/wlan1.ini | cut -d\/ -f2)"

if cat /etc/dhcpcd.conf | grep ipaddr
then
	sudo sed -i "s|<ipaddr>|${IP}|g" /etc/pihole/setupVars.conf
	sudo sed -i "s|<ipaddr>|${IP}|g" /etc/dhcpcd.conf
	sudo sed -i "s|<routeripaddr>|${ROUTERIP}|g" /etc/dhcpcd.conf
	sudo pihole enable
fi

if [[ "$APIPR"  != "$APBLOCKIPR" ]]
then
	sudo sed -i "s/${APBLOCKIPR}/${APIPR}/g" /etc/nginx/blockips
	sudo sed -i "s/${SSHBLOCKIPR}/${APIPRSHORT}/g" /etc/hosts.deny
fi


