#!/bin/bash
IP=$(ip -o -f inet addr show dev wlan0 | awk '/scope global/ {print $4}')
ROUTERIP=$(ip route show | grep -i 'default via'| awk '{print $3}')

sed -i "s|<ipaddr>|${IP}|g" /etc/pihole/setupVars.conf
sed -i "s|<ipaddr>|${IP}|g" /etc/dhcpcd.conf
sed -i "s|<routeripaddr>|${ROUTERIP}|g" /etc/dhcpcd.conf

sudo pihole enable

sudo reboot
