#!/bin/bash

#Variables
IP=$(ip route show | grep -i 'default via'| awk '{print $7}')
ROUTERIP=$(ip route show | grep -i 'default via'| awk '{print $3}')
intialpassword="secret"

#Add package repositories
# -Yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

#Update everything
apt update -y
apt upgrade -y
SKIP_WARNING=1 rpi-update
reboot

#Install scripts
for file in /etc/hubble/Scripts/*; do
    if [ -f "$f" ]; then
        chmod +x "$f"
        cp "$f" /usr/bin
    fi
done

#Change hostname
changehostname hubble

#Install dependencies
apt install lighttpd usbmount nodejs -y
wget http://downloads.fars-robotics.net/wifi-drivers/install-wifi -O /usr/bin/install-wifi
chmod +x /usr/bin/install-wifi

#Install yarn
apt install yarn -y
yarn install -cwd "/etc/hubble/Dashboard/"

#Install wifi driver
install-wifi

#Install RaspAP
curl -sL https://install.raspap.com | bash -s -- -r profwyattb/raspap-webgui -b master -y -o 0 -a 0
networkingpath=$(php -r 'require_once "/var/www/html/wifi/includes/config.php"; echo RASPI_CONFIG_NETWORKING;')
raspappath=$(php -r 'require_once "/var/www/html/wifi/includes/config.php"; echo RASPI_CONFIG;')
mv /etc/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
cp /etc/hubble/Wifi/config/wlan1.ini $networkingpath/wlan1
cp /etc/hubble/Wifi/config/raspap-hostapd.ini $raspappath/hostapd.ini
reboot

#Install PiHole

#Remove dnsmasq
apt remove dnsmasq -y
rm /etc/systemd/system/dnsmasq.service
rm /etc/init.d/dnsmasq
reboot

#Main PiHole install
echo 'IPV4_ADDRESS="'"$IP"'"' >> /etc/hubble/setupVars.conf
mkdir /etc/pihole/
cp /etc/hubble/PiHole/setupVars.conf /etc/pihole/setupVars.conf
/etc/hubble/PiHole/install.sh --unattended
cp /etc/hubble/PiHole/gravity.db /etc/pihole/gravity.db
pihole -g

#Making it work
touch /var/lib/misc/dnsmasq.leases
chown pihole:pihole /var/lib/misc/dnsmasq.leases
apt install php-sqlite3
pihole restartdns
pihole disable

#Configuration for IP addresses
sed -i "s/IPV4_ADDRESS=.*/IPV4_ADDRESS=<ipaddr>/g" /etc/pihole/setupVars.conf
sed -i "s|${IP}|<ipaddr>|g" /etc/dhcpcd.conf
sed -i "s|${ROUTERIP}|<routeripaddr>|g" /etc/dhcpcd.conf

#Install nginx

apt-get -y install nginx php7.3-fpm php7.3-cgi php7.3-xml php7.3-sqlite3 php7.3-intl apache2-utils
/etc/hubble/Dashboard/node_modules/.bin/pm2 start /home/pi/hubble/Dashboard/server.js
apt remove lighttpd
rm /etc/systemd/system/lighttpd.service
rm /etc/init.d/lighttpd
systemctl enable php7.3-fpm
systemctl enable nginx

#Need to copy nginx config -> /etc/nginx/sites-available/default
cp /etc/hubble/Config/nginx.conf /etc/nginx/sites-available/default
htpasswd -b -c /etc/nginx/.htpasswd admin $intialpassword
chown -R www-data:www-data /var/www/html
chmod -R 755 /var/www/html
usermod -aG pihole www-data

/etc/hubble/Dashboard/node_modules/.bin/pm2 start /etc/hubble/Dashboard/server.js
/etc/hubble/Dashboard/node_modules/.bin/pm2 save
/etc/hubble/Dashboard/node_modules/.bin/pm2 startup systemd
# env PATH=$PATH:/usr/bin /home/pi/hubble/Dashboard/node_modules/pm2/bin/pm2 startup systemd -u pi --hp /home/pi
# /etc/hubble/Dashboard/node_modules/.bin/pm2 save


#Install docker
curl -sSL https://get.docker.com | sh
#Change to admin
usermod -aG docker pi
apt install -y libffi-dev libssl-dev
apt install -y python3 python3-pip
apt remove python-configparser

#Docker install
mkdir /etc/hubble/File\ server/app/
chown -R www-data:www-data /etc/hubble/File\ server/app/
docker-compose up -d
docker exec -u www-data nextcloud php /var/www/html/occ app:enable files_external
apt install usbmount jq
chmod +x /home/pi/hubble/File\ server/Automounting/* 
cp /home/pi/hubble/File\ server/Automounting/mount.sh /etc/usbmount/mount.d/mount
cp /home/pi/hubble/File\ server/Automounting/unmount.sh /etc/usbmount/umount.d/unmount